spring:
  servlet:
    multipart:
      max-file-size: 20MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 密码
    # password: Chuangwo@zqt123
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 5
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池的最大数据库连接数
        max-active: 50
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:12580/company?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: qt
      password: Admin@qt123
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1 FROM DUAL
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow:
        url-pattern: /druid/*
      filter:
        stat:
          enabled: true
          # 慢Sql记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
logging:
  config: classpath:logback-spring.xml
  file:
    path: logs
  level:
    com.vpn.website.client.mapper: debug
mybatis-plus:
  configuration:
    # 打印 sql 语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
app:
  # 图片等文件放在这个目录下，可以直接访问到，相当于把文件放在webapps下
  filepath: /qttzzjUploads/
  fileMax: 20
  fortest: true
